version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gestion_user
    ports:
      - "3306:3306"

  myapp:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/gestion_user
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
